name = "Gay Party"
author = "STATIK228"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41e7fecba3bea1c5a779e831380194658829adadd0215d048e95ec17b00aea89"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
