name = "Gay Party"
author = "STATIK228"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df39a1f3e9c58a0fd9fde066c2fa0967fea89e252de0cdd05a397f823daaa5b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
