name = "Gay Party"
author = "STATIK228"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4434a257898277617ff8d9f2f2d17eb31bebaefec8afef4305e96c72c7f4d086"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
