# Cooldown players have after using the /rtp command
#Range: 1.0 ~ 100.0
cooldown = 30.0
#
#Minimum X coordinate rtp will use
#Range: -1000000.0 ~ 1000000.0
minX = -1000.0
# 
#aximum X coordinate rtp will use
#Range: -1000000.0 ~ 1000000.0
maxX = 1000.0
#
#Minimum Z coordinate rtp will use
#Range: -1000000.0 ~ 1000000.0
minZ = -1000.0
#
#Maximum Z coordinate rtp will use
#Range: -1000000.0 ~ 1000000.0
maxZ = 1000.0
#
#Time it takes to teleport players after using the /rtp command
#Range: 1.0 ~ 120.0
teleportTime = 5.0
#
#How many times rtp will retry to find a location to teleport the player if the first is invalid
#Range: 1.0 ~ 10.0
rtpAttempts = 5.0

